### ISSUE TITLE
Blacklist mini-ui is broken

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#106]
![image](https://cloud.githubusercontent.com/assets/842080/9025762/401c6cb2-3914-11e5-9eb0-1aae4330dba1.png)
The excuse text is white, the source overrides the excuse text, and the button to show it anyway falls under the post.

**Comment by ThePsionic** [comment]
About the text color, I found the following inline style but I'm not certain where it comes from. This code is preventing the blacklist color to show up.
```css
 .xblacklist_blacklisted_post .post_avatar, .xblacklist_blacklisted_post .post_permalink {
	 display: none !important;
 }

  .xblacklist_blacklisted_post .xblacklist_excuse {
	  position: absolute;
	 top: 0;
	 left: 0;
	 width: 100%;
	  color: rgba(255,255,255,.43);
	 height: 27px !important;
	 padding: 0px;
	 !important;
	  line-height: 27px !important;
	 padding-left: 15px;
	 !important;
 }

  .xblacklist_blacklisted_post .post_content {
	  background: transparent;
	 color: rgba(255,255,255,.43);
 }

  .xblacklist_blacklisted_post:hover .xblacklist_open_post {
	 display: block;
 }

  .xblacklist_blacklisted_post .xblacklist_open_post {
	  display: none;
	  
}

  .xblacklist_blacklisted_post .post_tags {
	 display: none;
 }

  .xblacklist_blacklisted_post {
	  height: 40px !important;
	  opacity: 1 !important;
	 padding: 0px !important;
	  box-shaddow: inset 0px 1px 0px rgba(255,255,255,0.10);
	  border: 1px dashed rgba(255,255,255,0.25);
	 background: transparent;
 }
```
